### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by igneus** [igneus/calendarium-romanum#13]
Great deal of the code has 100% test coverage, but there are still a few uncovered lines.

1. run `rake spec`, Simplecov will create new directory `coverage` with test coverage report
2. look into the report, choose an uncovered branch of code, write a spec reaching there
3. repeat until all files are 100% covered

**Comment by henriquepjv** [comment]
@igneus i will take a look for the remaining tests ✌

**Comment by igneus** [comment]
@henriquepjv Should you need any help, feel free to ask questions.

**Comment by igneus** [comment]
I don't want to have issues blocked by people who declared interest, but don't show any activity for an extended period of time. So:

@henriquepjv  you are, of course, still really welcome if you want to work on this, but so is anyone else.

**Comment by igneus** [comment]
Done.
