### ISSUE TITLE
Implement Calendar#each

### ISSUE THREAD

**Issue by igneus** [igneus/calendarium-romanum#14]
Iterating over days of the liturgical year, yielding `Day` instances.

**Comment by lao9** [comment]
I can take a crack at this feature!

**Comment by igneus** [comment]
I don't want to have small easy issues blocked by people who declared interest, but don't show any activity for an extended period of time. So:

@lao9 you are, of course, still very much welcome if you really want to work on this, but so is anyone else.

**Comment by lao9** [comment]
Thank you @igneus !
