### ISSUE TITLE
Improve the YARD API documentation

### ISSUE THREAD

**Issue by igneus** [igneus/calendarium-romanum#23]
There are a lot of undocumented or underdocumented methods, here and there descriptions may be outdated.

(Small PRs dealing with documentation of a single class or file are preferable.)

**Comment by aredshaw** [comment]
Are you using REST APIs? If so, I might be able to help.
What are the following?
* The base path
* Endpoints
* All possible methods and parameters
* An API Key (If required)

**Comment by igneus** [comment]
No, this is a Ruby library, not an application. By "API" [the library's public interface](https://en.wikipedia.org/wiki/Application_programming_interface#Libraries_and_frameworks) (classes and methods intended to be used by code using the library) is meant. [YARD](https://yardoc.org/) is a Ruby tool generating documentation from class/method comments. The current state of the documentation can be seen [here](https://www.rubydoc.info/github/igneus/calendarium-romanum/master).

**Comment by igneus** [comment]
Closing - the API documentation is mostly sufficient now.
