### ISSUE TITLE
Strange Phrasing - "Octave Day of Christmas, of Mary, Mother of God"

### ISSUE THREAD

**Issue by mkasberg** [igneus/calendarium-romanum#26]
I originally discovered this on [chruch-calendar-api](https://github.com/igneus/church-calendar-api), but it seemed more appropriate to open the issue here since it comes from this library (specifically, [config/locales/en.yml](https://github.com/igneus/calendarium-romanum/blob/master/config/locales/en.yml)).

The phrasing seems a little strange for this solemnity. The API returns something like [this](http://calapi.inadiutorium.cz/api/v0/en/calendars/default/2018/01/01):

```javascript
{
  "date": "2018-01-01",
  ...
  "celebrations": [
    {
      "title": "Octave Day of Christmas, of Mary, Mother of God",
      ...
    }
  ],
  ...
}
```

I'm not an expert on the church calendar, but I think it's the _Solemnity of Mary, Mother of God_. The "Octave Day of Christmas" isn't part of the solemnity, is it? As such, I think I'd expect something more like this:

```javascript
{
  "date": "2018-01-01",
  ...
  "celebrations": [
    {
      "title": "Mary, Mother of God",
      "colour": "white",
      "rank": "solemnity",
      "rank_num": 1.3
    },
    {
      "title": "Octave Day of Christmas",
      "colour": "white",
      "rank": ???,
      "rank_num": ???
    }
  ],
  ...
}
```

Alternatively, just change the title to something like: `"title": "Mary, Mother of God, and the Octave Day of Christmas"` or simply `"title": "Mary, Mother of God"`.

I'm really not sure what the best behavior is here, but the existing phrasing seemed a little strange to me and I thought it might be worth thinking about.

Anyway, it's really a pretty small issue one way or another. Thanks for all your work on this library and API.

**Comment by mkasberg** [comment]
Also, I wouldn't mind fixing this myself and opening a pull request, but I'd need a little direction on which fix seems best. :)

**Comment by igneus** [comment]
Thanks for opening this issue!

The current wording was probably taken from [this Wikipedia page](https://en.wikipedia.org/wiki/General_Roman_Calendar#January), where it is (probably less awkward) "Octave Day of Christmas, *Solemnity* of Mary, Mother of God".

The title may look strange as it's really result of a merge of two titles. In liturgical books I own (Czech, Latin) the two parts are usually printed with distinctive types ("Octave Day of Christmas" rather as a supertitle or kind of date, "Solemnity of Mary, Mother of God" as the main feast title). In a similar vein it's printed also in the Czech *ordo*. I have an English *ordo* of the diocese of East Anglia (GB), where it's just "Solemnity of Mary, The Holy Mother of God" - and nothing more.

For me the real question is "what is the official English title"? I must admit that for languages other than Czech I currently rely solely on various Internet resources, sometimes with questionable results. It would be best to get photos of the calendar as printed at the beginning of a missal or breviary (or in an appendix of the official English translation of the instruction *Calendarium Romanum*). That's what I would consider the most official wording and what I would thus prefer to follow.

**Comment by igneus** [comment]
I should add that the split in two celebrations considered above is not an option. The calendar ([here, page 23](https://archive.org/details/CalendariumRomanum1969)) is clear: it's a single solemnity (with a somewhat doubled name).
Also the calendar system doesn't allow coincidence of a solemnity with another celebration on a single day. In such case order of precedence applies and one of the coinciding celebrations is either transferred (only if both celebrations are solemnities) or suppressed.

**Comment by mkasberg** [comment]
That all makes sense. I'll see if I can figure out what the name is in some of those official English books.

**Comment by mkasberg** [comment]
Here is how it appears in _Shorter Christian Prayer_:

![img_20180103_220024](https://user-images.githubusercontent.com/12214617/34550949-56ee80ce-f0d2-11e7-9b3c-2e339ae4f1a5.jpg)

![img_20180103_215847](https://user-images.githubusercontent.com/12214617/34550952-5d90a100-f0d2-11e7-8187-30cff8f1b40b.jpg)

![img_20180103_215951](https://user-images.githubusercontent.com/12214617/34550956-6333c2c2-f0d2-11e7-8ce5-215ca4d68aeb.jpg)

**Comment by igneus** [comment]
Thanks a lot! Now how would you arrange the title in a single string value without any formatting?

PR most welcome (commits in project history are the best way of keeping record of due credits).

**Comment by mkasberg** [comment]
I think perhaps "Mary, Mother of God (Octave of Christmas)" makes the most sense. I can get a PR up later today.
