### ISSUE TITLE
French translation improvement

### ISSUE THREAD

**Issue by AzariasB** [igneus/calendarium-romanum#5]
This one is on me, but I don't know how to do it : 
In English, when counting the week's numbers  for example, you add a "th" (or "st" for  first "nd" for second and "rd" for third).
In french, there is the same thing : "_er_" for the first ("_premier_" in french) and ("_eme_" for the others).
There is also a really special case : when there are only two elements, you say "_second_" (2nd) and not "_deuxieme_"(2eme). But I don't know if this is feasible.

**Comment by igneus** [comment]
> But I don't know if this is feasible.

Yes, it is. Here is the class building ordinals https://github.com/igneus/calendarium-romanum/blob/master/lib/calendarium-romanum/ordinalizer.rb and here the specs https://github.com/igneus/calendarium-romanum/blob/master/spec/ordinalizer_spec.rb

**Comment by igneus** [comment]
@AzariasB Would you review the PR?

I think the special case "2nd" doesn't apply in the liturgical calendar, as we only use the ordinals for weeks of liturgical seasons and each of them has more than two weeks. The sole exception is the Christmas time. Can you check how the "2nd Sunday after Christmas" is spelled in official French liturgical calendars?

**Comment by igneus** [comment]
(The second Sunday after Christmas is quite a rare liturgical day, so even tracking down it's "official" French name might be complicated. It appeared e.g. in liturgical year 2013/14, on the 5th January 2014.)

**Comment by AzariasB** [comment]
Thanks for the link, I will review the PR :)

**Comment by igneus** [comment]
Closing. Reopen if necessary.
