### ISSUE TITLE
SanctoraleDumper

### ISSUE THREAD

**Issue by igneus** [igneus/calendarium-romanum#60]
It would be handy to have a class doing the opposite of what `SanctoraleLoader` does - serializing contents of a `Sanctorale` instance to the [standard data file format](https://github.com/igneus/calendarium-romanum/tree/master/data).

**Comment by mkasberg** [comment]
I'm planning on participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and looking for some fun things to work on - perhaps I could try to tackle this in the next couple weeks :slightly_smiling_face:

**Comment by igneus** [comment]
Sure. Contributions are welcome as always.

I planned to prepare some more ready-to-tackle issues (not only) for Hacktoberfest in calendarium-romanum as well as in some related projects ([calendarium-romanum-remote](https://github.com/igneus/calendarium-romanum-remote), [calrom](https://github.com/calendarium-romanum/calrom)), but I don't know if I'll make it before the beginning of October.
