### ISSUE TITLE
Travis CI: save resources

### ISSUE THREAD

**Issue by igneus** [igneus/calendarium-romanum#68]
Currently we unnecessarily consume Travis CI processor time by always running specs with all supported locales (`rake spec_all_locales`).

Our Travis CI configuration (`.travis.yml`) should be modified to only run this lengthy task on a single image (preferably the one with the newest supported MRI) and on the rest run just the normal (much faster) `rake spec`.

**Comment by zhmurko** [comment]
hi @igneus 
i would like to prepare a PR for this issue. Please assign it to me

**Comment by igneus** [comment]
Hi @zhmurko, great, thanks, looking forward to the PR.
In this project assigning people to issues is not in use, since the personal situation does not require it - there are no crowds of contributors fighting over issues.
