### ISSUE TITLE
`czech-cs.txt`: Inconsistent use of comma before `a druhů`

### ISSUE THREAD

**Issue by tukusejssirs** [igneus/calendarium-romanum#71]
While dealing with romcal/romcal#125, I have noticed that your strings in [`czech-cs.txt`](https://github.com/igneus/calendarium-romanum/blob/master/data/czech-cs.txt) sometimes contains commas before `a druhů`, sometimes not. I think this should be consistent.

I have no knowledge of the Czech grammar, however, I presume that in this it is quite similar to Slovak grammar.
1. Slovak liturgists (see lc.kbs.sk, which is absolutely consistent in information is provides with the published _Direktórium 2020_) prefer alway using comma before `a spoločníkov`.
2. However, all Slovak teachers prefer to omit it and regard the use of comma in such situations redundant, even grammatically incorrect.

For the purpose of this issue, I don’t care if you use or don’t use a comma before `a druhů`, just be consistent. Even better: share the info with me. :smiley:

**Comment by igneus** [comment]
I love pedantic proof-readers.

In Czech no comma is allowed between a simple name and "a druhů"

*Sv. Pavla Mikiho [no comma here] a druhů, mučedníků*

but it is compulsory if the name of the "principal companion" does not stand alone, but has a title attached.

*Sv. Augustina Žao Ronga, **kněze,** a druhů, mučedníků*

There was exactly one inconsistency (actually an orthography error), a fix is [on the way](https://youtu.be/11SFXwA4ahU?t=182).
