### ISSUE TITLE
Missing celebration in `czech-cs.txt`: Saint Teresa of Calcutta, religious

### ISSUE THREAD

**Issue by tukusejssirs** [igneus/calendarium-romanum#73]
I think you miss celebration of _Saint Teresa of Calcutta, religious_ (src: [katolik.cz](http://www.katolik.cz/kalendar/kalendar.asp?d=5&m=9&r=2020)). I don’t say that the source is an official, but still I think that she is celebrated in the Czech Republic (country-wide).

Potentially missing celebrations:
- _Saint Anthony Zaccaria, priest_:
   - it is inscribed into the GRC on 5 July, when we celebration St Cyril and Methodius, however, in Slovakia, we moved this celebration to 7 July (your bishops might have decided to omit the celebration though);
- _Saint Lawrence Ruiz and Companions, martyrs_:
   - it occurs with the solemnity of St Wenceslaus.

**Comment by tukusejssirs** [comment]
Slightly OT: Is this correct in Czech? → `Sv. Antonína Marie Zaccaria, kněze` … Is the genitive `Zaccaria` same as in nominative? It looks like it is (according to [catholica.cz](http://catholica.cz/?id=2919)), however, I (as Slovak) would use `Zaccarie`.

**Comment by igneus** [comment]
I recently proof-read the Czech calendar against multiple recent official sources, it's reliable. (The diocesan calendars not that much, though.)

Neither [Mother Teresa](https://github.com/igneus/calendarium-romanum/commit/29d5e073c3dcfc80c5f458c1477d851612df6b6b), nor Anthony Zaccaria, nor Lawrence Ruiz and companions are on the calendar of Czech dioceses.

**Comment by igneus** [comment]
> Is this correct in Czech? → Sv. Antonína Marie Zaccaria, kněze … Is the genitive Zaccaria same as in nominative?

Yes. Foreign names are by default not inflected.
