### ISSUE TITLE
Incorrect inflection of masculine name `Maria`

### ISSUE THREAD

**Issue by tukusejssirs** [igneus/calendarium-romanum#76]
I am not 100 % sure about this, however, the masculine name `Maria` is inflected differently from feminine name `Maria`.

According to [prirucka.jc.cas.cz](https://prirucka.ujc.cas.cz/?id=321), the genitive singular of the masculine name is `Marii`, however, in `czech-cs.txt` you have the following celebration names that are in contrary to this rule.

```js
28 de_montfort : Sv. Ludvíka Marie Grigniona z Montfortu, kněze
20 hofbauer : Sv. Klementa Marie Hofbauera, kněze
1 m alphonsus : Sv. Alfonsa Marie z Liguori, biskupa a učitele církve
4 m vianney : Sv. Jana Marie Vianneye, kněze
14 m R kolbe : Sv. Maxmiliána Marie Kolbeho, kněze a mučedníka
24 claret : Sv. Antonína Marie Klareta, biskupa
```

Note that I would create a PR for this, however, as I am not 100 % sure about this, I’d rather wait for your review.

**Comment by igneus** [comment]
I lack knowledge required to explain this phenomenon linguistically, but this is how names of these saints are written/said throughout Czech liturgical books and elsewhere, so it's definitely correct at least in this specific context ("Maria" as a male person's second name).

As you probably don't have any Czech liturgical books at home, [here is a quite official and reliable online source for the calendar of Czech and Moravian dioceses](http://www.liturgie.cz/temata/liturgicky-cas/cesky-narodni-kalendar). Variants deviating from it usually have no chance of being merged into calendarium-romanum.
